import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [transactions, setTransactions] = useState(null);

  useEffect(() => {
    const fetchTransactions = async () => {
      const res = await fetch("/api/transactions");
      const json = await res.json();

      if (res.ok) {
        setTransactions(json);
      }
    };

    fetchTransactions();
  }, []);

  console.log(transactions);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {transactions &&
          transactions.map((transaction, index) => {
            return (
              <div key={index}>
                <p>{transaction._id}</p>
                <p>{transaction.amount}</p>
                <p>{transaction.createdAt}</p>
                <p>{transaction.date}</p>
                <p>{transaction.description}</p>
                <p>{transaction.tag}</p>
              </div>
            );
          })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
